# OpenJazz makefile

CC=mipsel-linux-gcc
CXX=mipsel-linux-g++
INCLUDE=/opt/mipsel-linux-uclibc/usr/include

include openjazz.mk

OpenJazz: $(OBJS)
	$(CXX) -Wall -I$(INCLUDE) -I$(INCLUDE)/libmodplug -I$(INCLUDE)/SDL $(OBJS) -o OpenJazz -lSDL -lstdc++ -lz -lpthread /opt/mipsel-linux-uclibc/usr/lib/libmodplug.a

%.o: %.cpp
	$(CXX) -Wall -DDINGOO -DUSE_SOCKETS -DUSE_MODPLUG -I$(INCLUDE) -I$(INCLUDE)/libmodplug -I$(INCLUDE)/SDL -Isrc -O2 -c $< -o $@

clean:
	rm -f OpenJazz $(OBJS)
